In [2]:
import gtsam
import numpy as np


In [24]:
# import numpy as np

D = np.load("../D.npy")
gyro = D[:, [1, 2, 3]]

Sigma_gyro = np.cov(gyro.T)
bias_gyro = np.mean(gyro, axis=0)


print("Sigma_gyro", Sigma_gyro)
print("bias_gyro", bias_gyro)


accel = D[:, [4, 5, 6]]


Sigma_accel = np.cov(accel.T)
scale_accel = np.mean(np.linalg.norm(accel, axis=1))


print("Sigma_accel", Sigma_accel)
print("scale_accel", scale_accel)

Sigma_gyro [[ 5.55974355e-06 -8.15803043e-07 -6.86001271e-07]
 [-8.15803043e-07  1.33895015e-05 -8.05265053e-07]
 [-6.86001271e-07 -8.05265053e-07  9.32790369e-06]]
bias_gyro [ 0.00568885  0.01512006 -0.0259456 ]
Sigma_accel [[2.04732590e-04 4.20679038e-05 1.76100075e-05]
 [4.20679038e-05 7.81885879e-05 2.68170642e-06]
 [1.76100075e-05 2.68170642e-06 1.67431073e-05]]
scale_accel 0.9960030916001715


In [25]:
r = gtsam.Rot3()

In [36]:
def predict(r_0: gtsam.Rot3, P_0: np.ndarray, gyro: np.ndarray, sigma_gyro: np.ndarray, dt: float):
    d =  gtsam.Rot3().Expmap(gyro * dt)
    J_r0 = np.zeros((3, 3))
    J_d = np.zeros((3, 3))
    r = r_0.compose(d, J_r0, J_d)
    J_d *= dt
    P = J_r0 @ P_0 @ J_r0.transpose() + J_d @ sigma_gyro @ J_d.transpose()
    return r, P

In [37]:
r = gtsam.Rot3()
P = np.ones((3, 3)) * 0.02

In [38]:

for i in range(1, len(D)):
    r, P = predict(r, P, (D[i, [1, 2, 3]] + D[i-1, [1, 2, 3]])/2, Sigma_gyro, D[i, 0] - D[i-1, 0])

TypeError: compose(): incompatible function arguments. The following argument types are supported:
    1. (self: gtsam.gtsam.Rot3, p2: gtsam.gtsam.Rot3) -> gtsam.gtsam.Rot3

Invoked with: R: [
	1, 0, 0;
	0, 1, 0;
	0, 0, 1
]
, R: [
	1, 0.000282299, 0.000143803;
	-0.000282291, 1, -5.32835e-05;
	-0.000143818, 5.32429e-05, 1
]
, array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]]), array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:

predict(r, P, gyro, sigma_gyro, dt)

In [39]:
rrr = gtsam.Pose3

In [41]:
help(rrr)

Help on class Pose3 in module gtsam.gtsam:

class Pose3(pybind11_builtins.pybind11_object)
 |  Method resolution order:
 |      Pose3
 |      pybind11_builtins.pybind11_object
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  Adjoint(...)
 |      Adjoint(*args, **kwargs)
 |      Overloaded function.
 |      
 |      1. Adjoint(self: gtsam.gtsam.Pose3, xi: numpy.ndarray[numpy.float64[m, 1]]) -> numpy.ndarray[numpy.float64[6, 1]]
 |      
 |      2. Adjoint(self: gtsam.gtsam.Pose3, xi: numpy.ndarray[numpy.float64[m, 1]], H_this: numpy.ndarray[numpy.float64[m, n], flags.writeable, flags.f_contiguous], H_xib: numpy.ndarray[numpy.float64[m, n], flags.writeable, flags.f_contiguous]) -> numpy.ndarray[numpy.float64[6, 1]]
 |  
 |  AdjointMap(...)
 |      AdjointMap(self: gtsam.gtsam.Pose3) -> numpy.ndarray[numpy.float64[6, 6]]
 |  
 |  AdjointTranspose(...)
 |      AdjointTranspose(*args, **kwargs)
 |      Overloaded function.
 |      
 |      1. AdjointTranspose(self: gtsam.gtsa